name: Update README with Recent GitHub Activity

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    name: Update this repo's README with recent GitHub activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.1
        with:
          COMMIT_MSG: "Updated recent activity"
          MAX_LINES: 5  # Number of recent activities to show
          GH_USERNAME: pessima-au
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          TARGET_FILE: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add the token here
